#!/usr/bin/env bash

# Install dependencies
sudo apt update && sudo apt upgrade
sudo apt install unzip git wget vim

# Download & Unzip public-dotfiles
wget -O /tmp/public-dotfiles.zip \
    https://github.com/aakashhemadri/public-dotfiles/archive/refs/heads/master.zip
unzip /tmp/public-dotfiles.zip -d /tmp

cd /tmp/public-dotfiles-master
source init.sh
echo -e "Making dots executable..."
sudo chmod +x $HOME/.local/bin/dots
source $DOTS_SOURCE/env.sh
echo -e "Configuring dot files..."
dots config use arch-remote
echo -e "Installing dot files..."
dots install -vr
source $HOME/.profile
vim +'PlugInstall --sync' +qa
