#!/usr/bin/env bash

curl -s -o- https://install.aakashhemadri.com/arch/config/vm.creds.json > /tmp/vm.creds.json

archinstall \
    --config https://install.aakashhemadri.com/arch/config/vm.config.json \
    --creds /tmp/vm.creds.json \
    --silent